### ISSUE TITLE
Install-WebApplicationProxy never runs

### ISSUE THREAD

**Issue by toastman2k** [ChrisLGardner/WebApplicationProxyDSC#4]
If Install-WebApplicationProxy has not previously been run doesn't the try/catch @lines 88-93 fail to run Function ConfigureWAP?

I must be using the resource wrong, little help?

**Comment by ChrisLGardner** [comment]
The way DSC resources work is that Get won't be called unless you run Get-DscConfiguration at the command line. When attempting to apply the configuration for the first time Test will run, produce $false as it isn't configured and then run Set to configure it.

Do you have an example of the configuration you're trying to apply? Any log files from it failing?

**Comment by toastman2k** [comment]
You're exactly right, I was running Get-DscConfiguration and therefore
getting the following error;

VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Starting retrieving Web Applucation Proxy
configuration.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Add-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Remove-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Set-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyAvailableADFSRelyingParty'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyConfiguration'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Set-WebApplicationProxyConfiguration'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Add-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Remove-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Set-WebApplicationProxyApplication'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyAvailableADFSRelyingParty'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Get-WebApplicationProxyConfiguration'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting function
'Set-WebApplicationProxyConfiguration'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting cmdlet
'Get-WebApplicationProxyHealth'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting cmdlet
'Get-WebApplicationProxySslCertificate'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting cmdlet
'Install-WebApplicationProxy'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting cmdlet
'Set-WebApplicationProxySslCertificate'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting cmdlet
'Update-WebApplicationProxyDeviceRegistration'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'gwpa'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'swpa'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'rwpa'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'awpa'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'gwpc'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'swpc'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'gwpr'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Exporting alias 'gwph'.
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Retrieving trust certificate...
*VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Error occurred while retrieving Web
Application Proxy configuration: You cannot perform this action because Web
Application Proxy has not been configured. Run the*
*Install-WebApplicationProxy PowerShell command, and then try again.*
*The system cannot find the file specified.*
* (0x80070002)*
VERBOSE: [WIN-6T5O17UNC5K]:
[[WapConfiguration]WAPInstall] Finished retrieving Web Applucation Proxy
configuration.
VERBOSE: [WIN-6T5O17UNC5K]: LCM:  [ End    Get      ]
[[WapConfiguration]WAPInstall]  in 0.3910 seconds.

Any plans to tack on Add-ADFSFarmNode in future?

Many thanks for your response!

**Comment by ChrisLGardner** [comment]
I'm glad that's solved the issue you were having.

Add-ADFSFarmNode will likely end up as another resource in [cADFS](https://github.com/ChrisLGardner/cADFS). Can you add an issue there so I can keep track of it?
